GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gogoinggoen_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gogoinggoen_app;
GRANT EXECUTE ON FUNCTION admin_reset_all_mutable_state() TO gogoinggoen_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gogoinggoen_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO gogoinggoen_app;
