services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: vera-vault-backend
    environment:
      VAULT_TOKEN: PV6QKm8XtToPXK4G4u9uatWRX9GQlERnawgC31Uj5qb8KypnHVzPpNusmb84GdDvJZq
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: vera-vault-frontend
    ports:
      - "35667:80"
    depends_on:
      - backend
    restart: unless-stopped
